-- =============================================================================
-- 0003_network_routine: persist inbox reply drafts + per-area campaign goals.
--
-- These two tables back the routine surface on the Network Area page and
-- generalize so the same pattern serves Apply / Learn / Share / Earn later.
-- 100% additive.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- inbox_reply_drafts: Claude-drafted replies to inbound Gmail threads warranting
-- a response. Generated by the area_picker network branch, surfaced in the
-- BriefingCard, written to Gmail drafts via Composio.
-- -----------------------------------------------------------------------------
create table hmart.inbox_reply_drafts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  gmail_thread_id text not null,
  gmail_message_id text not null,
  sender_email text not null,
  sender_name text,
  subject text,
  snippet text,
  drafted_body text not null,
  confidence text not null check (confidence in ('known', 'warm', 'starred')),
  contact_id uuid references hmart.network_contacts(id) on delete set null,
  generated_at timestamptz not null default now(),
  status text not null default 'pending'
    check (status in ('pending', 'drafted_in_gmail', 'dismissed', 'sent')),
  gmail_draft_id text,
  gmail_draft_url text,
  picker_run_id uuid references hmart.picker_runs(id) on delete set null,
  unique (user_id, gmail_thread_id)
);

create index inbox_reply_drafts_user_status_idx
  on hmart.inbox_reply_drafts(user_id, status);
create index inbox_reply_drafts_picker_run_idx
  on hmart.inbox_reply_drafts(picker_run_id);

-- -----------------------------------------------------------------------------
-- area_goals: campaign-style goal tracking attached to an Area.
-- Network gets the first row (EO-May 2026, 20 outreaches, 5x4 sub-tally).
-- Status predicate is a flexible JSON shape so each area can define its own
-- "what counts as progress" query without schema churn.
-- -----------------------------------------------------------------------------
create table hmart.area_goals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  area_id uuid not null references hmart.areas(id) on delete cascade,
  name text not null,
  target int not null check (target > 0),
  category_targets jsonb,
  deadline date,
  status_predicate jsonb not null,
  started_at timestamptz not null default now(),
  active boolean not null default true,
  unique (user_id, area_id, name)
);

create index area_goals_active_idx on hmart.area_goals(user_id, area_id, active);

-- -----------------------------------------------------------------------------
-- RLS
-- -----------------------------------------------------------------------------
alter table hmart.inbox_reply_drafts enable row level security;
alter table hmart.area_goals enable row level security;

create policy "inbox_reply_drafts_owner"
  on hmart.inbox_reply_drafts
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "area_goals_owner"
  on hmart.area_goals
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- -----------------------------------------------------------------------------
-- Seed EO-May 2026 goal for any existing user that has a network area.
-- Idempotent via the unique (user_id, area_id, name) constraint.
-- -----------------------------------------------------------------------------
insert into hmart.area_goals (
  user_id, area_id, name, target, category_targets, deadline, status_predicate
)
select
  a.user_id,
  a.id,
  'EO-May 2026',
  20,
  '{"podcast":5,"publication":5,"gallery":5,"peer":5}'::jsonb,
  date '2026-05-31',
  jsonb_build_object(
    'status', jsonb_build_array('contacted', 'responded', 'in_relationship'),
    'vault_section_prefix', 'Cold funnel',
    'last_touch_at_gte', '2026-05-01'
  )
from hmart.areas a
where a.slug = 'network'
on conflict (user_id, area_id, name) do nothing;
